; Althera - fonte de tensão inteligente
; ESP32-S3-WROOM-2-N16R8 = 16MB flash OCTAL + 8MB PSRAM OCTAL (GPIO35/36/37 ficam reservados)

[env:althera]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1

board_build.arduino.memory_type = opi_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.flash_mode = opi

monitor_speed = 115200
upload_speed = 921600

; USB_CDC_ON_BOOT = Serial pela USB nativa. Se usar a porta USB-UART, remova essa linha.
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0